# -*- coding: utf-8 -*-
"""Clinical_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qggloIh5Qvtu2lbLb2lHj_aKq-758pib
"""

pip install faiss-cpu sentence-transformers transformers torch rank-bm25 pypdf

from pypdf import PdfReader

def load_pdf(file_path):
    reader = PdfReader(file_path)
    text = ""

    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"

    return text


# 👉 Replace with your PDF path
raw_text = load_pdf("tribe.pdf")

print(raw_text[:500])  # Inspect first 500 characters

"""## Clean Text

"""

import os
import re

def clean_text(text):
    # Remove multiple spaces
    text = re.sub(r'\s+', ' ', text)

    # Remove multiple newlines
    text = re.sub(r'\n+', '\n', text)

    return text.strip()


cleaned_text = clean_text(raw_text)

print("\nCLEANED TEXT:\n")
print(cleaned_text[:500])

"""## Chunking (Character-based with Overlap)

"""

def chunk_text(text, chunk_size=500, overlap=100):
    """
    Splits on sentence endings so chunks don't cut mid-sentence.
    Falls back to character split only if no sentence boundary found.
    """
    sentences = re.split(r'(?<=[.?!])\s+', text)
    chunks = []
    current_chunk = ""

    for sentence in sentences:
        if len(current_chunk) + len(sentence) <= chunk_size:
            current_chunk += " " + sentence
        else:
            if current_chunk.strip():
                chunks.append(current_chunk.strip())
            # Start new chunk with overlap from end of last chunk
            overlap_text = current_chunk[-overlap:] if len(current_chunk) > overlap else current_chunk
            current_chunk = overlap_text + " " + sentence

    if current_chunk.strip():
        chunks.append(current_chunk.strip())

    return chunks

def is_valid_chunk(chunk, min_words=30):
    words = chunk.split()
    if len(words) < min_words:
        return False
    if chunk.count('...') > 3:
        return False
    if chunk.count('....') > 2:
        return False
    roman = re.findall(r'\b(i{1,3}|iv|v|vi{1,3}|ix|x)\b', chunk.lower())
    if len(roman) > 5:
        return False
    return True

chunks = chunk_text(cleaned_text, chunk_size=600, overlap=100)
chunks = [c for c in chunks if is_valid_chunk(c)]  # ← ADD THIS

print(f"\nTotal chunks after filtering: {len(chunks)}")
print("\n=== CHUNK 0 ===\n", chunks[0])
print("\n=== CHUNK 1 ===\n", chunks[1])

"""## STEP 2 — Embeddings + FAISS"""

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

embed_model = SentenceTransformer('all-MiniLM-L6-v2')
chunk_embeddings = embed_model.encode(chunks, show_progress_bar=True)

index = faiss.IndexFlatL2(chunk_embeddings.shape[1])
index.add(np.array(chunk_embeddings, dtype=np.float32))

print(f"\nEmbedding shape: {chunk_embeddings.shape}")  # (num_chunks, 384)

"""## BM25 (Keyword Search)
## This is building a keyword-based search engine on your chunks.
"""

from rank_bm25 import BM25Okapi

tokenized_chunks = [chunk.lower().split() for chunk in chunks]  # FIX: lowercase for better matching
bm25 = BM25Okapi(tokenized_chunks)

"""## Hybrid Retrieval (KEY PART)"""

def reciprocal_rank_fusion(ranked_lists, k=60):
    """Merge multiple ranked lists using RRF scoring."""
    scores = {}
    for ranked in ranked_lists:
        for rank, idx in enumerate(ranked):
            scores[idx] = scores.get(idx, 0) + 1 / (k + rank + 1)
    return sorted(scores, key=scores.get, reverse=True)

def hybrid_search(query, k=5):
    # --- FAISS semantic search ---
    query_embedding = embed_model.encode([query], convert_to_numpy=True)
    _, faiss_indices = index.search(np.array(query_embedding, dtype=np.float32), k)
    faiss_ranked = list(faiss_indices[0])

    # --- BM25 keyword search ---
    tokenized_query = query.lower().split()          # FIX: lowercase to match tokenized_chunks
    bm25_scores = bm25.get_scores(tokenized_query)
    bm25_ranked = list(np.argsort(bm25_scores)[::-1][:k])  # FIX: descending order

    # --- Combine via Reciprocal Rank Fusion ---
    combined_indices = reciprocal_rank_fusion([faiss_ranked, bm25_ranked])[:k]
    return [chunks[i] for i in combined_indices], combined_indices

"""## MMR (Diversity)"""

from sklearn.metrics.pairwise import cosine_similarity

def mmr(query, retrieved_chunks, lambda_param=0.7, top_k=4):
    if not retrieved_chunks:
        return []

    query_emb = embed_model.encode([query])           # shape: (1, 384)
    chunk_embs = embed_model.encode(retrieved_chunks)  # shape: (n, 384)

    selected = []
    candidate_indices = list(range(len(retrieved_chunks)))

    while len(selected) < top_k and candidate_indices:
        scores = []
        for i in candidate_indices:
            emb = chunk_embs[i].reshape(1, -1)                          # FIX: explicit reshape
            relevance = cosine_similarity(query_emb, emb)[0][0]

            if selected:
                # FIX: compare against already-selected embeddings properly
                selected_embs = chunk_embs[selected]
                diversity = max(cosine_similarity(emb, selected_embs.reshape(len(selected), -1))[0])
            else:
                diversity = 0.0

            score = lambda_param * relevance - (1 - lambda_param) * diversity
            scores.append((i, score))

        best_idx = max(scores, key=lambda x: x[1])[0]
        selected.append(best_idx)
        candidate_indices.remove(best_idx)

    return [retrieved_chunks[i] for i in selected]

"""## Reranker"""

from sentence_transformers import CrossEncoder

reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

def rerank(query, chunks):
    if not chunks:
        return []
    pairs = [[query, chunk] for chunk in chunks]
    scores = reranker.predict(pairs)
    ranked = sorted(zip(chunks, scores), key=lambda x: x[1], reverse=True)
    return [chunk for chunk, _ in ranked]

"""## LLM Answer"""

from groq import Groq

client = Groq(api_key=os.getenv("GROQ_API_KEY", ""))

SYSTEM_PROMPT = (
    "You are a neuroscience research assistant. "
    "Answer questions using ONLY the provided context. "
    "If the answer is not clearly supported by the context, "
    "start your response with 'NOT FOUND:' and explain why."
)

# CHAT WITH MEMORY
chat_history = []

def chat(query, context_chunks=None):
    if context_chunks is None:
        results, _ = hybrid_search(query, k=12)
        mmr_results = mmr(query, retrieved_chunks=results, top_k=4)
        context_chunks = rerank(query, mmr_results)

    context = " ".join(context_chunks[:4])[:3000]
    last_period = context.rfind('.')
    if last_period > 500:
        context = context[:last_period + 1]

    user_message = f"Context:\n{context}\n\nQuestion: {query}"
    chat_history.append({"role": "user", "content": user_message})

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "system", "content": SYSTEM_PROMPT}] + chat_history,
        temperature=0.2,
        max_tokens=512
    )

    reply = response.choices[0].message.content
    chat_history.append({"role": "assistant", "content": reply})
    return reply

def reset_chat():
    global chat_history
    chat_history = []
    print("Chat history cleared.")

def expand_and_answer(original_query):
    expansion_response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": (
                    f"Generate 3 alternative phrasings of this question "
                    f"for searching a neuroscience research paper. "
                    f"Return only the questions, one per line, no numbering.\n\n"
                    f"Question: {original_query}"
                )
            }
        ],
        temperature=0.5,
        max_tokens=200
    )
    alt_queries = expansion_response.choices[0].message.content.strip().split('\n')
    all_queries = [original_query] + alt_queries

    print("Trying these query variants:")
    for q in all_queries:
        print(f"  → {q}")

    all_chunks = []
    for q in all_queries:
        results, _ = hybrid_search(q, k=6)
        all_chunks.extend(results)

    seen = set()
    unique_chunks = []
    for chunk in all_chunks:
        if chunk not in seen:
            seen.add(chunk)
            unique_chunks.append(chunk)

    print(f"Total unique chunks retrieved: {len(unique_chunks)}")

    mmr_results = mmr(original_query, unique_chunks, top_k=5)
    reranked = rerank(original_query, mmr_results)
    return chat(original_query, reranked)

# RUN
answer = chat(query, reranked_chunks)
print("\n" + "="*50)
print("FINAL ANSWER:")
print("="*50)
print(answer)

# Follow-up question
followup = chat("Can you elaborate on how the modalities differ?")
print("\n" + "="*50)
print("FOLLOW-UP ANSWER:")
print("="*50)
print(followup)

query = "What does 'multisensory integration' refer to in the context of TRIBE v2's latent features?"

results, result_indices = hybrid_search(query, k=12)
mmr_results = mmr(query, retrieved_chunks=results, top_k=4)
reranked_chunks = rerank(query, mmr_results)

answer = chat(query, reranked_chunks)
print(answer)

# ── STEP 2: IF ANSWER STARTS WITH NOT FOUND, USE EXPANSION ──
if answer.startswith("NOT FOUND"):
    print("\nTrying query expansion...\n")
    expanded_answer = expand_and_answer(query)
    print(expanded_answer)

